version: 2
updates:
- package-ecosystem: "docker"
  directory: "/.github/workflows"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    basemaps:
      patterns:
        - "@basemaps/*"
    aws:
      patterns:
        - "@aws-sdk/*"
    chunkd:
      patterns:
        - "@cogeotiff/*"
        - "@chunkd/*"
  ignore:
    - dependency-name: "@aws-sdk/*"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "@types/node"
      update-types: ["version-update:semver-patch"]
